### ISSUE TITLE
makepkg fails

### ISSUE THREAD

**Issue by Blutkoete** [ros-noetic-arch/ros-noetic-pcl-ros#2]
Hello,

makepkg of this package fails currently. It appears to be an incompatibility with pcl:

`/opt/ros/noetic/include/ros/message_traits.h:120:28: error: ‘__s_getMD5Sum’ is not a member of ‘std::shared_ptr<const pcl::PCLPointCloud2>’`

I attached the whole build log.

Is there anything I can do to help you with this matter?

[ros-noetic-pcl-ros_makepkg_-ms_output.txt](https://github.com/ros-noetic-arch/ros-noetic-pcl-ros/files/5609482/ros-noetic-pcl-ros_makepkg_-ms_output.txt)

**Comment by acxz** [comment]
@Blutkoete thanks for the error log, let me try to reproduce the error on my end and maybe I can glean some info.
My first hunch is that this package needs to be updated.

**Comment by acxz** [comment]
Yep, upgrading the package resolved the issue for me, just pushed `1.7.2` out to the aur.
Feel free to comment on this issue if you are still experiencing errors.

**Comment by alexdewar** [comment]
I'm still getting build errors :cry: 

```
/home/alex/.cache/yay/ros-noetic-pcl-ros/src/perception_pcl-1.7.2/pcl_ros/src/pcl_ros/filters/voxel_grid.cpp: In member function ‘void pcl_ros::VoxelGrid::config_callback(pcl_ros::VoxelGridConfig&, uint32_t)’:
/home/alex/.cache/yay/ros-noetic-pcl-ros/src/perception_pcl-1.7.2/pcl_ros/src/pcl_ros/filters/voxel_grid.cpp:86:51: error: ‘class pcl_ros::VoxelGridConfig’ has no member named ‘min_points_per_voxel’
   86 |   if (minPointsPerVoxel != ((unsigned int) config.min_points_per_voxel))
      |                                                   ^~~~~~~~~~~~~~~~~~~~
/home/alex/.cache/yay/ros-noetic-pcl-ros/src/perception_pcl-1.7.2/pcl_ros/src/pcl_ros/filters/voxel_grid.cpp:88:32: error: ‘class pcl_ros::VoxelGridConfig’ has no member named ‘min_points_per_voxel’
   88 |     minPointsPerVoxel = config.min_points_per_voxel;
      |                                ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pcl_ros_filters.dir/build.make:147: CMakeFiles/pcl_ros_filters.dir/src/pcl_ros/filters/voxel_grid.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2871: CMakeFiles/pcl_ros_filters.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
 done.
```

I've rebuilt ros-noetic-pcl-conversions, ros-noetic-pcl-msgs and ros-noetic-perception-pcl, but I'm still getting this problem.

(Perhaps this issue could be reopened so that others can see it?)

**Comment by acxz** [comment]
hmm This is a different issue, ideally I would ask you to make another issue thread, but its fine :stuck_out_tongue_winking_eye: 

Just to confirm are you using `arch4edu`? If you are let's try rebuilding without using it.

This error seems like an upstream issue, but I'm surprised I didn't encounter it. 

Do you mind posting the entire build log?

My hunch is that there might be a missing dep we are not building against. Or one of the dependencies haven't been updated.

**Comment by acxz** [comment]
Here is a related upstream issue: https://github.com/ros-perception/perception_pcl/issues/272

I would just do a complete rebuild of all deps recursively. Like `yay -Syu ros-noetic-pcl-ros --rebuildtree`.
If that still doesn't fix, I really don't know.

**Comment by alexdewar** [comment]
Yes I was using ``arch4edu``. I got it working eventually by rebuilding as you suggested, but I also had to delete ``~/.ros`` -- I think there was something fishy in the cache.

Thanks for your help!

**Comment by acxz** [comment]
Glad to hear you got it working!
