### ISSUE TITLE
‘ConvexHull’ in namespace ‘pcl’ does not name a template type

### ISSUE THREAD

**Issue by petronny** [ros-noetic-arch/ros-noetic-pcl-ros#9]
First `openmpi`, `nlohmann-json` and `glew` are additionally installed to solve some cmake errors.

Then this error shows:
```
In file included from /build/ros-noetic-pcl-ros/src/perception_pcl-1.7.5/pcl_ros/src/pcl_ros/surface/convex_hull.cpp:39:
/build/ros-noetic-pcl-ros/src/perception_pcl-1.7.5/pcl_ros/include/pcl_ros/surface/convex_hull.h:76:12: error: ‘ConvexHull’ in namespace ‘pcl’ does not name a template type
   76 |       pcl::ConvexHull<pcl::PointXYZ> impl_;
      |            ^~~~~~~~~~
```
Seems like a pcl 1.13 compatibility issue.

https://github.com/arch4edu/cactus/actions/runs/4343635498/jobs/7612077223

**Comment by petronny** [comment]
As suggested in https://github.com/arch4edu/arch4edu/issues/218#issuecomment-1467422016 , it's fixed by installing `qhull` during the build. `openmpi`, `nlohmann-json`, `glew`, `fmt` are also needed to finally build this package.

**Comment by acxz** [comment]
Thanks for keeping up with this issue. Deps are added in [4d9d371](https://github.com/ros-noetic-arch/ros-noetic-pcl-ros/commit/4d9d3713828a04ee304de9a96f2355411c37a304)
